spring:
  application:
    name: Ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerse
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
