spring:
  application:
    name: multi-vendor-platform

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:test-dummy-jwt-token}
  expiration: 1800000

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    reset-password-path: ${RESET_PASSWORD_PATH:/resetpassword}

  email:
    enabled: ${EMAIL_ENABLED:false}
    from: ${EMAIL_FROM:noreply.shermatov@gmail.com}

springdoc:
  api-docs:
      enabled: false